[package]
name = "serpent"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["Lars Viklund <zao@zao.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
block-cipher-trait = "^0.6"
byteorder = "^1.3"